# Generated by Django 6.0 on 2026-04-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardio',
            old_name='Workout',
            new_name='workout',
        ),
    ]
