# Generated by Django 6.0.3 on 2026-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_sets',
            field=models.IntegerField(),
        ),
    ]
