# Generated by Django 6.0 on 2026-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_alter_exercise_exercise_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(to='fitness_app.exercise')),
            ],
        ),
    ]
