# Generated by Django 6.0 on 2026-04-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_rename_workout_cardio_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cardio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.cardio')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_logs', to='fitness_app.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
