# Generated by Django 6.0 on 2026-04-07 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_profile_current_streak_profile_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateTimeField(default=datetime.date(2026, 4, 6)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
