# Generated by Django 6.0 on 2026-04-07 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_alter_profile_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(default=datetime.date(2026, 4, 6)),
        ),
    ]
