# Generated by Django 6.0 on 2026-04-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_alter_profile_last_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(null=True),
        ),
    ]
