# Generated by Django 6.0 on 2026-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_alter_profile_last_activity_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'workout'), name='unique_active_session_per_user_workout'),
        ),
    ]
